### Alfian Syam Sabila_A11.2019.12210


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('kelulusan.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Informatika' 20.0 3.7]
 ['Matematika' 18.0 2.6]
 ['Fisika' 20.0 nan]
 ['Informatika' 19.0 3.1]
 ['Informatika' 23.0 3.5]
 ['Fisika' nan 3.2]
 ['Matematika' 24.0 3.3]
 ['Matematika' 19.0 2.8]
 ['Informatika' 20.0 3.5]
 ['Fisika' 21.0 3.2]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
print(x_train)

[['Informatika' 23.0 3.5]
 ['Fisika' 21.0 3.2]
 ['Matematika' 18.0 2.6]
 ['Matematika' 24.0 3.3]
 ['Matematika' 19.0 2.8]
 ['Informatika' 19.0 3.1]
 ['Informatika' 20.0 3.7]
 ['Fisika' nan 3.2]]


In [ ]:
print(x_test)

[['Fisika' 20.0 nan]
 ['Informatika' 20.0 3.5]]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Informatika' 20.0 3.7]
 ['Matematika' 18.0 2.6]
 ['Fisika' 20.0 3.2111111111111112]
 ['Informatika' 19.0 3.1]
 ['Informatika' 23.0 3.5]
 ['Fisika' 20.444444444444443 3.2]
 ['Matematika' 24.0 3.3]
 ['Matematika' 19.0 2.8]
 ['Informatika' 20.0 3.5]
 ['Fisika' 21.0 3.2]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 20.0 3.7]
 [0.0 0.0 1.0 18.0 2.6]
 [1.0 0.0 0.0 20.0 3.2111111111111112]
 [0.0 1.0 0.0 19.0 3.1]
 [0.0 1.0 0.0 23.0 3.5]
 [1.0 0.0 0.0 20.444444444444443 3.2]
 [0.0 0.0 1.0 24.0 3.3]
 [0.0 0.0 1.0 19.0 2.8]
 [0.0 1.0 0.0 20.0 3.5]
 [1.0 0.0 0.0 21.0 3.2]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 0 0 1 1 1 0 0 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 24.0 3.3]
 [0.0 1.0 0.0 23.0 3.5]
 [0.0 1.0 0.0 20.0 3.7]
 [0.0 1.0 0.0 19.0 3.1]
 [0.0 0.0 1.0 18.0 2.6]
 [0.0 0.0 1.0 19.0 2.8]
 [0.0 1.0 0.0 20.0 3.5]
 [1.0 0.0 0.0 20.444444444444443 3.2]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 20.0 3.2111111111111112]
 [1.0 0.0 0.0 21.0 3.2]]


In [ ]:
print(y_train)

[0 1 1 1 0 0 1 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:,3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 1.8520869081516291 0.25144742283748456]
 [0.0 1.0 0.0 1.333214311315375 0.8261843893231647]
 [0.0 1.0 0.0 -0.2234034791933881 1.400921355808845]
 [0.0 1.0 0.0 -0.7422760760296424 -0.3232895436481943]
 [0.0 0.0 1.0 -1.2611486728658967 -1.7601319598623935]
 [0.0 0.0 1.0 -0.7422760760296424 -1.1853949933767145]
 [0.0 1.0 0.0 -0.2234034791933881 0.8261843893231647]
 [1.0 0.0 0.0 0.007206563844946338 -0.03592106040535421]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 -0.2234034791933881 -0.0039912289339276786]
 [1.0 0.0 0.0 0.2954691176428662 -0.03592106040535421]]
